# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         News-Verimod
version:      0.50
version_from: Version.pm
installdirs:  site
requires:
    News::Gateway:                 0.43

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
